### ISSUE TITLE
unable to build on ios

### ISSUE THREAD

**Issue by Faisalkc4u** [vkpdeveloper/flutterpaytm#1]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Xcode build done.                                           14.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/ios/Classes/SwiftPaytmPlugin.swift:3:8: error: module compiled with Swift 4.2.1 cannot be imported by the Swift 5.1.3 compiler: /Users/faisalkc/store/ios/.symlinks/plugins/paytm/ios/PaymentSDK.framework/Modules/PaymentSDK.swiftmodule/x86_64.swiftmodule
    import PaymentSDK
           ^
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Comment by vkpdeveloper** [comment]
Sorry for this issue this plugin is currently available only for Android Platform. Please wait in next release it will available for iOS too.
